resource "datadog_dashboard_json" "geth_dashboard_json" {
  dashboard = <<EOF
{
   "title":"Geth Overview",
   "description":"## Title\n\nMonitor geth client metrics",
   "widgets":[
      {
         "id":2763665031852150,
         "definition":{
            "title":"Database Chaindata",
            "type":"group",
            "background_color":"vivid_green",
            "show_title":true,
            "layout_type":"ordered",
            "widgets":[
               {
                  "id":2581907624401514,
                  "definition":{
                     "title":"Database Chaindata Read ",
                     "title_size":"16",
                     "title_align":"left",
                     "show_legend":true,
                     "legend_layout":"auto",
                     "legend_columns":[
                        "avg",
                        "min",
                        "max",
                        "value",
                        "sum"
                     ],
                     "type":"timeseries",
                     "requests":[
                        {
                           "formulas":[
                              {
                                 "formula":"query1"
                              }
                           ],
                           "response_format":"timeseries",
                           "queries":[
                              {
                                 "query":"avg:geth.eth.db.chaindata.disk_read_mean{*}",
                                 "data_source":"metrics",
                                 "name":"query1"
                              }
                           ],
                           "style":{
                              "palette":"dog_classic",
                              "line_type":"solid",
                              "line_width":"normal"
                           },
                           "display_type":"line"
                        }
                     ]
                  },
                  "layout":{
                     "x":0,
                     "y":0,
                     "width":4,
                     "height":2
                  }
               },
               {
                  "id":38199385525651,
                  "definition":{
                     "title":"Database Chaindata Write",
                     "title_size":"16",
                     "title_align":"left",
                     "show_legend":false,
                     "legend_layout":"auto",
                     "legend_columns":[
                        "avg",
                        "min",
                        "max",
                        "value",
                        "sum"
                     ],
                     "time":{
                        
                     },
                     "type":"timeseries",
                     "requests":[
                        {
                           "formulas":[
                              {
                                 "formula":"query1"
                              }
                           ],
                           "response_format":"timeseries",
                           "queries":[
                              {
                                 "query":"avg:geth.eth.db.chaindata.disk_write_mean{*}",
                                 "data_source":"metrics",
                                 "name":"query1"
                              }
                           ],
                           "style":{
                              "palette":"dog_classic",
                              "line_type":"solid",
                              "line_width":"normal"
                           },
                           "display_type":"line"
                        }
                     ]
                  },
                  "layout":{
                     "x":4,
                     "y":0,
                     "width":4,
                     "height":2
                  }
               }
            ]
         },
         "layout":{
            "x":0,
            "y":0,
            "width":12,
            "height":3
         }
      },
      {
         "id":3225224794919580,
         "definition":{
            "title":"P2P Stats",
            "type":"group",
            "background_color":"vivid_blue",
            "show_title":true,
            "layout_type":"ordered",
            "widgets":[
               {
                  "id":6182732669901307,
                  "definition":{
                     "title":"P2P Egress/Ingress",
                     "title_size":"16",
                     "title_align":"left",
                     "show_legend":true,
                     "legend_layout":"auto",
                     "legend_columns":[
                        "avg",
                        "min",
                        "max",
                        "value",
                        "sum"
                     ],
                     "time":{
                        
                     },
                     "type":"timeseries",
                     "requests":[
                        {
                           "formulas":[
                              {
                                 "formula":"query1"
                              },
                              {
                                 "formula":"query2"
                              }
                           ],
                           "queries":[
                              {
                                 "name":"query1",
                                 "data_source":"metrics",
                                 "query":"avg:geth.p2p.egress_mean{*}"
                              },
                              {
                                 "name":"query2",
                                 "data_source":"metrics",
                                 "query":"avg:geth.p2p.ingress_mean{*}"
                              }
                           ],
                           "response_format":"timeseries",
                           "style":{
                              "palette":"dog_classic",
                              "line_type":"solid",
                              "line_width":"normal"
                           },
                           "display_type":"line"
                        }
                     ]
                  },
                  "layout":{
                     "x":0,
                     "y":0,
                     "width":4,
                     "height":2
                  }
               },
               {
                  "id":8955040736057778,
                  "definition":{
                     "title":"# of P2P Dials",
                     "title_size":"16",
                     "title_align":"left",
                     "show_legend":true,
                     "legend_layout":"auto",
                     "legend_columns":[
                        "avg",
                        "min",
                        "max",
                        "value",
                        "sum"
                     ],
                     "time":{
                        
                     },
                     "type":"timeseries",
                     "requests":[
                        {
                           "formulas":[
                              {
                                 "formula":"query1"
                              }
                           ],
                           "queries":[
                              {
                                 "name":"query1",
                                 "data_source":"metrics",
                                 "query":"avg:geth.p2p.dials_count{*}"
                              }
                           ],
                           "response_format":"timeseries",
                           "style":{
                              "palette":"dog_classic",
                              "line_type":"solid",
                              "line_width":"normal"
                           },
                           "display_type":"line"
                        }
                     ]
                  },
                  "layout":{
                     "x":4,
                     "y":0,
                     "width":4,
                     "height":2
                  }
               },
               {
                  "id":2606396176948916,
                  "definition":{
                     "title":"P2P Avg Dials",
                     "title_size":"16",
                     "title_align":"left",
                     "show_legend":true,
                     "legend_layout":"auto",
                     "legend_columns":[
                        "avg",
                        "min",
                        "max",
                        "value",
                        "sum"
                     ],
                     "time":{
                        
                     },
                     "type":"timeseries",
                     "requests":[
                        {
                           "formulas":[
                              {
                                 "formula":"query1"
                              }
                           ],
                           "queries":[
                              {
                                 "name":"query1",
                                 "data_source":"metrics",
                                 "query":"avg:geth.p2p.dials_mean{*}"
                              }
                           ],
                           "response_format":"timeseries",
                           "style":{
                              "palette":"dog_classic",
                              "line_type":"solid",
                              "line_width":"normal"
                           },
                           "display_type":"line"
                        }
                     ]
                  },
                  "layout":{
                     "x":8,
                     "y":0,
                     "width":4,
                     "height":2
                  }
               }
            ]
         },
         "layout":{
            "x":0,
            "y":3,
            "width":12,
            "height":3
         }
      }
   ],
   "template_variables":[
      
   ],
   "layout_type":"ordered",
   "is_read_only":false,
   "notify_list":[
      
   ],
   "reflow_type":"fixed",
   "id":"3wk-5bg-8k4"
}
EOF
}